### ISSUE TITLE
Username should always match the e-mail address

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#21]
If the e-mail is over 50 characters, we can sha-1 the e-mail to generate the username.
Relations should use the user GUID instead of the username.

**Comment by fschwiet** [comment]
I do not think I understand this one.  The User table has an int primary key named UserId.  I would expect relations to the user table to use that primary key.

  It looks like User.UserName and User.Email are currently storing the same values.  If we want to have a persons username permanently reflect their email, I would consider dropping the UserName column, modifying WebSecurity.InitializeDatabaseConnection to use the Email column instead of UserName.  If we go down this route, we should also fix the registration page to only accept valid email addresses in the 'username' field.

  I am probably missing something though, as I do not see the need to make the column fit in 50 characters via sha-1.

  Internally, the membership code creates tables webpages_Membership and webpages_OAuthMembership, and both those have foreign keys based on column User.UserId.  When using the membership API, it often wants a UserName value.  That UserName value is used to look up the User.UserId before persisting any relationships.  It looks like we could configure the membership code to use the Email column instead of UserName by modifying the call to WebSecurity.InitializeDatabaseConnection in MembershipBoot).

**Comment by lilith** [comment]
I believe the problem was that User.UserName cannot be over 50 characters, yet e-mail addresses frequently are.  Whatever we need to do to ensure consistency and support for e-mail lengths > 50 chars.

**Comment by lilith** [comment]
MembershopBoot.cs generated accounts use non-email usernames

**Comment by fschwiet** [comment]
TL&DR:  I'd like to start storing a unique GUID in User.UserName.

Current issues:
- We have a redundant User.UserName and User.Email column, which are _usually_ the email.  They are different:
  - for the original admin user
  - when the user changes their email
    - If the user changes their email with our current code, they still have to use their old email when logging in.
    - If we update the email change option to update User.Username (in addition to User.Email) then the user has a corrupted login cookie and our site crashes.

Options:
1. Update User.Username when the user changes their email, and log the out after we update their email + User.UserName.  This solution is incomplete as it could leave bad auth cookies on other computers/browsers the user uses.
2. Start storing a unique guid as User.UserName (string).  This value would not be exposed to the user.  It would only be used by the membership system.
   - the guid is not based on the email because we want to allow the user to change their email without breaking references the membership system cares about.
   - when the user logs in locally (or changes their password), we'd use the database once to map email->guid so we can pass the guid as the username to the membership system.

**Comment by fschwiet** [comment]
I went ahead and made the suggested changes (User.UserName is now a guid used only as a membership user identifier) in the master branch of the new public repository (final commit was https://github.com/imazen/keyhub/commit/019bb955551506f9124265a20d2b31d54c518dd7)
