### ISSUE TITLE
Support DB storage of shared secret keys for transaction REST service

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#39]

**Comment by fschwiet** [comment]
I believe you said these secret keys are currently embedded in the code.  Can you point me to where in the code?

**Comment by lilith** [comment]
https://github.com/imazen/keyhub/blob/master/src/KeyHub.Web/Api/Controllers/TransactionByIpnController.cs#L47

**Comment by fschwiet** [comment]
I'm not sure where to put a UI the vendors can access.  We have the vendor edit page (http://i.imgur.com/wiMLMMu.png) but I believe that is for KeyHub admins.  For now, I'm going to extend the vendor edit page to list/modify the available shared secret keys after the list of public/private keys (since I think we'll need that UI there anyhow).

The key stored will be a symmetric key, a simple string value.  When stored in the database, should it be encrypted in the same manner as PrivateKeys.KeyBytes?

**Comment by fschwiet** [comment]
Any thoughts on what we call the shared secret in the user interface?  Shared secret doesn't really clue the user in what it is for, maybe we should call it an "API Key" / "Transaction Creation Key"?

**Comment by lilith** [comment]
Credential name / credential value ? 

EjunkieHandshake would be the name for the instance I'm using

**Comment by lilith** [comment]
Can we close this out?

**Comment by fschwiet** [comment]
Yes.  (this credentials are managed from the vendor page and stored in the VendorCredentials table)
