### ISSUE TITLE
Deploy to AppHarbor

### ISSUE THREAD

**Issue by lilith** [imazen/keyhub#55]

**Comment by fschwiet** [comment]
Just noting what needed to be done get it running on appharbor:
1)  The https->http url redirection wasn't working because AppHarbor ends the SSL at their load balancer.  Added code to do the redirect based off of a header the loadbalancer provides.
2)  Added AppHarbor.sln, which is Keyhub.sln without the integration tests.  This needs to be updated when new projects are added.  I added a AppHarbor.sln.readme.txt to walk through how to do this (its not hard, but probably something that will surprise someone down the road when appharbor doesn't see their project)
3) SQL configuration needed to be updated at https://sequelizer.apphb.com/database.  The "connection alias" configuration needs to be set to the connection string name that entity framework is using.
